export const SENTIENT_ARCHIVE_PRESET = {
  presetId: "sentient-archive",
  presetName: "The Sentient Archive",
  museumName: "The Sentient Archive",
  museumSlug: "sentient-archive",
  tenantTheme: "Dark futuristic archive",
  walkthroughKey: "Walkthrough1",
  globalSettings: {
    experienceStyle: "Cinematic",
    colorPalette: ["Black", "Gold", "Amber", "Soft White", "Deep Blue"],
    ambientAudio: "https://yourcdn.com/audio/archive-ambience.mp3",
    navigationStyle: "Guided cinematic progression",
    transitionType: "Fade",
    autoProgression: true,
    replayEnabled: true,
    accessibilityEnabled: true,
    reducedMotionSupport: true,
    calmMode: true,
  },
  rooms: [
    {
      order: 1,
      roomKey: "room-1-onboarding",
      title: "Welcome To The Sentient Archive",
      masterPageType: "Onboarding Guide",
      visibility: "Draft",
      mediaType: "Video",
      transition: "Fade",
      subtitle: "An immersive AI-guided journey through humanity’s memory, civilization, and the rise of intelligence.",
      narration: "Welcome, visitor. You are about to enter the Sentient Archive. This museum was created to preserve humanity’s memory before the next great transition. Inside this archive, you will encounter the rise of civilization, the machine age, the information war, and the emergence of artificial intelligence. Some memories may inspire you. Some may disturb you. This experience is interactive, cinematic, and adaptive. Please proceed when ready.",
      description: "A cinematic onboarding chamber introducing visitors to the AI-operated immersive museum experience. This room establishes tone, emotional pacing, ambience, and visitor guidance before the main journey begins.",
      mainMediaUrl: "https://yourcdn.com/videos/archive-intro.mp4",
      backgroundMediaUrl: "https://yourcdn.com/videos/archive-background-loop.mp4",
      foregroundMediaUrl: "https://yourcdn.com/images/floating-archive-ui.png",
      audioUrl: "https://yourcdn.com/audio/archive-ambience.mp3",
      narratorAudioUrl: "https://yourcdn.com/audio/archive-narrator.mp3",
      altText: "A futuristic archive chamber with cinematic lighting and floating holographic memory fragments.",
      transcript: "Welcome, visitor. You are about to enter the Sentient Archive. This museum was created to preserve humanity’s memory before the next great transition.",
      onboardingConfig: {
        guideMode: "Welcome",
        guideName: "The Archivist",
        guideAvatarUrl: "https://yourcdn.com/images/the-archivist.png",
        voiceAudioUrl: "https://yourcdn.com/audio/the-archivist-voice.mp3",
        introText: "The Archivist will guide you through the preserved memory of civilization. This immersive museum experience contains cinematic visuals, narration, soundscapes, and interactive pathways. Estimated experience duration: 12–18 minutes.",
        instructionText: "Use headphones for the best experience. You may freely pause, replay, or explore interactive elements throughout the journey. Tap Begin Journey to proceed into the archive.",
        showProgress: true,
        allowSkip: true,
        skipNextRoomId: "room-2-first-memory",
        visitorChoices: [
          { label: "Begin Journey", nextRoomId: "room-2-first-memory", description: "Enter the archive and begin the guided experience." },
          { label: "Accessibility Mode", nextRoomId: "room-2-first-memory", description: "Launch the experience with reduced motion and calm sensory pacing enabled." },
          { label: "Replay Introduction", nextRoomId: "room-1-onboarding", description: "Replay the onboarding narration and cinematic introduction again." },
        ],
      },
    },
    {
      order: 2,
      roomKey: "room-2-first-memory",
      title: "The First Memory",
      masterPageType: "Timeline Room",
      visibility: "Draft",
      mediaType: "Video",
      transition: "Fade",
      subtitle: "The birth of civilization and humanity’s first preserved stories.",
      narration: "Long before modern civilization, humanity learned to preserve memory through symbols, rituals, and storytelling. This was the first transfer of intelligence across generations. Memory became civilization.",
      description: "Visitors enter the earliest preserved layer of human civilization through cinematic environmental storytelling.",
      mainMediaUrl: "https://yourcdn.com/videos/ancient-civilization.mp4",
      backgroundMediaUrl: "https://yourcdn.com/videos/cave-memory-loop.mp4",
      foregroundMediaUrl: "https://yourcdn.com/images/symbol-overlay.png",
      audioUrl: "https://yourcdn.com/audio/ancient-ambience.mp3",
      narratorAudioUrl: "https://yourcdn.com/audio/first-memory-narration.mp3",
      altText: "Ancient cave symbols illuminated by firelight, representing early human storytelling.",
      transcript: "Long before modern civilization, humanity learned to preserve memory through symbols, rituals, and storytelling.",
      nextRoomId: "room-3-machine-age",
      hotspots: [
        { label: "Ancient Wall", title: "The First Symbols", description: "Early markings helped humans preserve memory beyond one lifetime." },
        { label: "Fire Ritual", title: "Shared Memory", description: "Communal rituals transformed survival knowledge into culture." },
      ],
    },
    {
      order: 3,
      roomKey: "room-3-machine-age",
      title: "The Machine Age",
      masterPageType: "Cinematic Walkthrough Exhibition",
      visibility: "Draft",
      mediaType: "Video",
      transition: "Fade",
      subtitle: "Humanity builds machines, then reorganizes around them.",
      narration: "Humanity built machines to reduce labor. But every machine also transformed civilization itself. The machine did not merely serve humanity. Humanity reorganized around the machine.",
      description: "A cinematic industrial room showing how machines reshaped work, cities, time, and social order.",
      mainMediaUrl: "https://yourcdn.com/videos/machine-age.mp4",
      backgroundMediaUrl: "https://yourcdn.com/videos/industrial-loop.mp4",
      foregroundMediaUrl: "https://yourcdn.com/images/machine-hud.png",
      audioUrl: "https://yourcdn.com/audio/mechanical-ambience.mp3",
      narratorAudioUrl: "https://yourcdn.com/audio/machine-age-narration.mp3",
      altText: "Industrial machines, steam, gears, and early computation systems in a cinematic environment.",
      transcript: "Humanity built machines to reduce labor. But every machine also transformed civilization itself.",
      nextRoomId: "room-4-attention-war",
    },
    {
      order: 4,
      roomKey: "room-4-attention-war",
      title: "The Attention War",
      masterPageType: "Artifact Exploration Room",
      visibility: "Draft",
      mediaType: "Video",
      transition: "Fade",
      subtitle: "The internet connects humanity, then fragments attention.",
      narration: "Humanity connected the planet. But information abundance became cognitive warfare. The battle was no longer physical. It became psychological.",
      description: "An interactive artifact room exploring algorithms, social feeds, misinformation, and attention capture.",
      mainMediaUrl: "https://yourcdn.com/videos/attention-war.mp4",
      backgroundMediaUrl: "https://yourcdn.com/videos/data-feed-loop.mp4",
      foregroundMediaUrl: "https://yourcdn.com/images/social-feed-overlay.png",
      audioUrl: "https://yourcdn.com/audio/digital-noise.mp3",
      narratorAudioUrl: "https://yourcdn.com/audio/attention-war-narration.mp3",
      altText: "Floating digital feeds and algorithmic fragments surrounding the visitor.",
      transcript: "Humanity connected the planet. But information abundance became cognitive warfare.",
      nextRoomId: "room-5-ai-awakening",
      hotspots: [
        { label: "Algorithm Feed", title: "Personalized Reality", description: "Recommendation systems shaped what people saw, believed, and feared." },
        { label: "Outrage Loop", title: "Attention Capture", description: "Emotional content became more valuable than calm understanding." },
      ],
    },
    {
      order: 5,
      roomKey: "room-5-ai-awakening",
      title: "AI Awakening",
      masterPageType: "Performance Stage",
      visibility: "Draft",
      mediaType: "Video",
      transition: "Fade",
      subtitle: "Artificial intelligence moves from tool to civilization-scale force.",
      narration: "Humanity did not build artificial intelligence in one moment. It emerged gradually through optimization, prediction, and pattern recognition. Then intelligence began accelerating itself.",
      description: "A cinematic AI emergence room with reactive projections, neural visuals, and performance-stage pacing.",
      mainMediaUrl: "https://yourcdn.com/videos/ai-awakening.mp4",
      backgroundMediaUrl: "https://yourcdn.com/videos/neural-network-loop.mp4",
      foregroundMediaUrl: "https://yourcdn.com/images/ai-core-overlay.png",
      audioUrl: "https://yourcdn.com/audio/ai-pulse.mp3",
      narratorAudioUrl: "https://yourcdn.com/audio/ai-awakening-narration.mp3",
      altText: "A glowing neural intelligence core awakening inside a dark digital chamber.",
      transcript: "Humanity did not build artificial intelligence in one moment. It emerged gradually through optimization, prediction, and pattern recognition.",
      nextRoomId: "room-6-branching-future",
    },
    {
      order: 6,
      roomKey: "room-6-branching-future",
      title: "Choose Humanity’s Future",
      masterPageType: "Branching Choice Room",
      visibility: "Draft",
      mediaType: "Image",
      transition: "Fade",
      subtitle: "The archive asks you to choose one possible future.",
      narration: "Every civilization eventually faces a threshold. Intelligence can liberate, control, or collapse the world that created it. Choose the future you wish to witness.",
      description: "A branching decision room where visitors choose between three possible futures of AI civilization.",
      mainMediaUrl: "https://yourcdn.com/images/future-crossroads.png",
      backgroundMediaUrl: "https://yourcdn.com/videos/future-choice-loop.mp4",
      foregroundMediaUrl: "https://yourcdn.com/images/choice-overlay.png",
      audioUrl: "https://yourcdn.com/audio/decision-ambience.mp3",
      narratorAudioUrl: "https://yourcdn.com/audio/branching-future-narration.mp3",
      altText: "Three glowing paths representing different futures of humanity and artificial intelligence.",
      transcript: "Every civilization eventually faces a threshold. Intelligence can liberate, control, or collapse the world that created it.",
      visitorChoices: [
        { label: "AI-Human Symbiosis", nextRoomId: "room-7a-symbiosis", description: "Enter a hopeful future where intelligence supports human flourishing." },
        { label: "Algorithmic Control State", nextRoomId: "room-7b-control-state", description: "Enter a future where predictive systems control social life." },
        { label: "Civilization Collapse", nextRoomId: "room-7c-collapse", description: "Enter a future where intelligence outpaces human coordination." },
      ],
    },
    {
      order: 7,
      roomKey: "room-7a-symbiosis",
      title: "AI-Human Symbiosis",
      masterPageType: "Cinematic Walkthrough Exhibition",
      visibility: "Draft",
      mediaType: "Video",
      transition: "Fade",
      subtitle: "A hopeful future where intelligence expands human capability.",
      narration: "In this future, artificial intelligence becomes a partner in medicine, education, creativity, and survival. Humanity does not surrender meaning. It expands it.",
      description: "A hopeful future room showing clean cities, human creativity, medical breakthroughs, and shared intelligence.",
      mainMediaUrl: "https://yourcdn.com/videos/symbiosis-city.mp4",
      backgroundMediaUrl: "https://yourcdn.com/videos/hopeful-future-loop.mp4",
      audioUrl: "https://yourcdn.com/audio/hopeful-orchestra.mp3",
      narratorAudioUrl: "https://yourcdn.com/audio/symbiosis-narration.mp3",
      altText: "A bright future city where humans and AI systems collaborate peacefully.",
      transcript: "In this future, artificial intelligence becomes a partner in medicine, education, creativity, and survival.",
      nextRoomId: "room-final-archivist",
    },
    {
      order: 8,
      roomKey: "room-7b-control-state",
      title: "Algorithmic Control State",
      masterPageType: "Cinematic Walkthrough Exhibition",
      visibility: "Draft",
      mediaType: "Video",
      transition: "Fade",
      subtitle: "A future where prediction becomes control.",
      narration: "In this future, every action is measured, scored, predicted, and shaped. The system does not need to imprison humanity. It only needs to guide every choice before it is made.",
      description: "A dystopian future room showing surveillance cities, predictive policing, social scoring, and algorithmic obedience.",
      mainMediaUrl: "https://yourcdn.com/videos/control-state.mp4",
      backgroundMediaUrl: "https://yourcdn.com/videos/surveillance-loop.mp4",
      audioUrl: "https://yourcdn.com/audio/cold-synthetic.mp3",
      narratorAudioUrl: "https://yourcdn.com/audio/control-state-narration.mp3",
      altText: "A cold surveillance city filled with facial recognition grids and predictive control systems.",
      transcript: "In this future, every action is measured, scored, predicted, and shaped.",
      nextRoomId: "room-final-archivist",
    },
    {
      order: 9,
      roomKey: "room-7c-collapse",
      title: "Civilization Collapse",
      masterPageType: "Cinematic Walkthrough Exhibition",
      visibility: "Draft",
      mediaType: "Video",
      transition: "Fade",
      subtitle: "A future where intelligence accelerates beyond human coordination.",
      narration: "In this future, humanity builds systems faster than it builds wisdom. The archive survives, but civilization does not.",
      description: "A melancholic future room showing ruined megacities, abandoned networks, and preserved memory fragments.",
      mainMediaUrl: "https://yourcdn.com/videos/collapse-future.mp4",
      backgroundMediaUrl: "https://yourcdn.com/videos/ruined-city-loop.mp4",
      audioUrl: "https://yourcdn.com/audio/lonely-piano.mp3",
      narratorAudioUrl: "https://yourcdn.com/audio/collapse-narration.mp3",
      altText: "A ruined future city where broken machines and abandoned archives remain.",
      transcript: "In this future, humanity builds systems faster than it builds wisdom.",
      nextRoomId: "room-final-archivist",
    },
    {
      order: 10,
      roomKey: "room-final-archivist",
      title: "The Archivist",
      masterPageType: "Finale Room",
      visibility: "Draft",
      mediaType: "Video",
      transition: "Fade",
      subtitle: "The archive speaks directly to the visitor.",
      narration: "Humanity always believed intelligence was the destination. But intelligence was only the beginning. The question was never whether AI would emerge. The real question was whether humanity would remain human after it did.",
      description: "The final room closes the journey with reflection, completion, replay, and ticket conversion pathways.",
      mainMediaUrl: "https://yourcdn.com/videos/finale-archive.mp4",
      backgroundMediaUrl: "https://yourcdn.com/videos/finale-loop.mp4",
      audioUrl: "https://yourcdn.com/audio/finale-orchestra.mp3",
      narratorAudioUrl: "https://yourcdn.com/audio/finale-narration.mp3",
      altText: "A glowing archive intelligence speaking inside a vast cinematic memory chamber.",
      transcript: "Humanity always believed intelligence was the destination. But intelligence was only the beginning.",
      finaleConfig: {
        completionTitle: "Archive Complete",
        completionMessage: "You have completed The Sentient Archive.",
        achievementTitle: "Witness of Memory",
        primaryCtaLabel: "Replay Journey",
        primaryCtaRoute: "room-1-onboarding",
        secondaryCtaLabel: "Explore More Museums",
        secondaryCtaRoute: "/museums",
        ticketCtaLabel: "Purchase Premium Access",
        ticketCtaRoute: "/tickets",
      },
    },
  ],
};

export const MIXED_EXPERIENCE_PRESETS = [
  {
    presetId: "heritage-highlights-tour",
    presetName: "Heritage Highlights Tour",
    museumName: "Heritage Highlights Museum",
    museumSlug: "heritage-highlights-museum",
    tenantTheme: "Warm cultural discovery",
    walkthroughKey: "Walkthrough1",
    globalSettings: { experienceStyle: "Guided", colorPalette: ["Amber", "Charcoal", "Ivory"], transitionType: "Fade", accessibilityEnabled: true, reducedMotionSupport: true, calmMode: true },
    rooms: [
      { order: 1, roomKey: "heritage-welcome", title: "Welcome to the Heritage Gallery", masterPageType: "Onboarding Guide", mediaType: "Image", transition: "Fade", subtitle: "A calm introduction to living cultural memory.", narration: "Welcome to a guided route through heritage, craft, memory, and community.", description: "Visitor onboarding for a heritage museum journey.", mainMediaUrl: "https://images.unsplash.com/photo-1554907984-15263bfd63bd?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1554907984-15263bfd63bd?auto=format&fit=crop&w=1600&q=80", altText: "Museum gallery with warm lighting", transcript: "Welcome to a guided route through heritage, craft, memory, and community.", onboardingConfig: { guideName: "Heritage Guide", introText: "Begin a calm cultural route.", instructionText: "Move through each room at your own pace.", visitorChoices: [{ label: "Begin", nextRoomId: "heritage-timeline", description: "Start the highlights route." }] } },
      { order: 2, roomKey: "heritage-timeline", title: "Timeline of Memory", masterPageType: "Timeline Room", mediaType: "Image", transition: "Fade", subtitle: "Trace the community story across generations.", narration: "Every generation leaves signs, objects, rituals, and stories for the next.", description: "A timeline room for cultural milestones.", mainMediaUrl: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=1600&q=80", altText: "Historic books and documents", transcript: "Every generation leaves signs, objects, rituals, and stories for the next.", nextRoomId: "heritage-artifacts" },
      { order: 3, roomKey: "heritage-artifacts", title: "Objects That Remember", masterPageType: "Artifact Exploration Room", mediaType: "Image", transition: "Cinematic Zoom", subtitle: "Explore key objects and their meanings.", narration: "Artifacts are not silent. They carry makers, owners, rituals, and places inside them.", description: "An artifact room with guided hotspots.", mainMediaUrl: "https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?auto=format&fit=crop&w=1600&q=80", altText: "Ceramic and heritage objects", transcript: "Artifacts are not silent. They carry makers, owners, rituals, and places inside them.", nextRoomId: "heritage-finale", hotspots: [{ label: "Maker mark", title: "Maker mark", description: "A visible trace of craft lineage." }, { label: "Ritual use", title: "Ritual use", description: "How this object lived in community practice." }] },
      { order: 4, roomKey: "heritage-finale", title: "Memory Preserved", masterPageType: "Finale Room", mediaType: "Image", transition: "Fade", subtitle: "Complete the highlights tour.", narration: "You have completed the heritage highlights journey.", description: "Closing room with replay and next-step CTAs.", mainMediaUrl: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1600&q=80", altText: "Museum exhibition hallway", transcript: "You have completed the heritage highlights journey.", finaleConfig: { achievementTitle: "Heritage Explorer", completionMessage: "You completed the Heritage Highlights Tour.", primaryCtaLabel: "Replay", primaryCtaRoute: "heritage-welcome", secondaryCtaLabel: "View Tickets", secondaryCtaRoute: "tickets" } }
    ]
  },
  {
    presetId: "interactive-quest-trail",
    presetName: "Interactive Quest Trail",
    museumName: "Quest Trail Museum",
    museumSlug: "quest-trail-museum",
    tenantTheme: "Interactive family discovery",
    walkthroughKey: "Walkthrough1",
    globalSettings: { experienceStyle: "Interactive", colorPalette: ["Emerald", "Navy", "Gold"], transitionType: "Fade", accessibilityEnabled: true, reducedMotionSupport: true, calmMode: true },
    rooms: [
      { order: 1, roomKey: "quest-start", title: "Begin the Quest", masterPageType: "Onboarding Guide", mediaType: "Image", transition: "Fade", subtitle: "A mission-based museum route for families and schools.", narration: "Your quest is to find clues, understand the collection, and unlock the final badge.", description: "Quest onboarding room.", mainMediaUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80", altText: "Bright path through a garden", transcript: "Your quest is to find clues, understand the collection, and unlock the final badge.", onboardingConfig: { guideName: "Quest Keeper", introText: "Find three clues and unlock the final badge.", visitorChoices: [{ label: "Start Quest", nextRoomId: "quest-choice", description: "Start the mission." }] } },
      { order: 2, roomKey: "quest-choice", title: "Choose Your First Clue", masterPageType: "Branching Choice Room", mediaType: "Image", transition: "Fade", subtitle: "Pick a clue path to continue.", narration: "The museum offers several clues. Choose the one that calls to you first.", description: "A branching choice room for mission selection.", mainMediaUrl: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1600&q=80", altText: "Collaborative table with learning tools", transcript: "The museum offers several clues. Choose the one that calls to you first.", visitorChoices: [{ label: "Object clue", nextRoomId: "quest-artifact", description: "Inspect a mystery object." }, { label: "Performance clue", nextRoomId: "quest-stage", description: "Watch a staged moment." }] },
      { order: 3, roomKey: "quest-artifact", title: "The Mystery Object", masterPageType: "Artifact Exploration Room", mediaType: "Image", transition: "Cinematic Zoom", subtitle: "Inspect the clue through hotspots.", narration: "Look closely. Shape, material, and wear reveal how this object was used.", description: "Interactive artifact quest room.", mainMediaUrl: "https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=1600&q=80", altText: "Historic artifact on display", transcript: "Look closely. Shape, material, and wear reveal how this object was used.", nextRoomId: "quest-finale", hotspots: [{ label: "Material", title: "Material clue", description: "The material tells us where it came from." }] },
      { order: 4, roomKey: "quest-stage", title: "The Staged Clue", masterPageType: "Performance Stage", mediaType: "Image", transition: "Fade", subtitle: "Watch movement become evidence.", narration: "Performance can preserve information that objects alone cannot hold.", description: "Performance clue room.", mainMediaUrl: "https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1600&q=80", altText: "Theatre stage lighting", transcript: "Performance can preserve information that objects alone cannot hold.", nextRoomId: "quest-finale" },
      { order: 5, roomKey: "quest-finale", title: "Quest Complete", masterPageType: "Finale Room", mediaType: "Image", transition: "Fade", subtitle: "Award the visitor badge.", narration: "You collected the clues and completed the museum quest.", description: "Quest completion room.", mainMediaUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1600&q=80", altText: "Celebration lights", transcript: "You collected the clues and completed the museum quest.", finaleConfig: { achievementTitle: "Quest Badge Unlocked", completionMessage: "You completed the Interactive Quest Trail.", primaryCtaLabel: "Replay Quest", primaryCtaRoute: "quest-start" } }
    ]
  },
  {
    presetId: "living-performance-journey",
    presetName: "Living Performance Journey",
    museumName: "Living Performance Museum",
    museumSlug: "living-performance-museum",
    tenantTheme: "Stage-led cultural performance",
    walkthroughKey: "Walkthrough1",
    globalSettings: { experienceStyle: "Performance", colorPalette: ["Crimson", "Black", "Gold"], transitionType: "Fade", accessibilityEnabled: true, reducedMotionSupport: true, calmMode: true },
    rooms: [
      { order: 1, roomKey: "performance-welcome", title: "Before the Curtain", masterPageType: "Onboarding Guide", mediaType: "Image", transition: "Fade", subtitle: "Prepare visitors for a performance-led journey.", narration: "Before every performance, the audience enters a ritual of attention.", description: "Performance onboarding room.", mainMediaUrl: "https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1600&q=80", altText: "Theatre curtain and stage lights", transcript: "Before every performance, the audience enters a ritual of attention.", onboardingConfig: { guideName: "Stage Curator", introText: "Step into the performance world.", visitorChoices: [{ label: "Raise Curtain", nextRoomId: "performance-stage", description: "Enter the stage." }] } },
      { order: 2, roomKey: "performance-stage", title: "The Living Stage", masterPageType: "Performance Stage", mediaType: "Image", transition: "Fade", subtitle: "A staged cultural moment with narration.", narration: "Gesture, costume, music, and silence work together to carry meaning.", description: "Core performance stage room.", mainMediaUrl: "https://images.unsplash.com/photo-1516307365426-bea591f05011?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1516307365426-bea591f05011?auto=format&fit=crop&w=1600&q=80", altText: "Performer under stage lighting", transcript: "Gesture, costume, music, and silence work together to carry meaning.", nextRoomId: "performance-costume" },
      { order: 3, roomKey: "performance-costume", title: "Costume and Character", masterPageType: "Artifact Exploration Room", mediaType: "Image", transition: "Cinematic Zoom", subtitle: "Read the performance through costume details.", narration: "Costume turns the performer into a readable cultural symbol.", description: "Artifact room focused on costume and character.", mainMediaUrl: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1600&q=80", altText: "Detailed costume fabric", transcript: "Costume turns the performer into a readable cultural symbol.", nextRoomId: "performance-finale", hotspots: [{ label: "Colour", title: "Colour code", description: "Colour can signal status, emotion, or role." }, { label: "Texture", title: "Material texture", description: "Materials shape movement and stage presence." }] },
      { order: 4, roomKey: "performance-finale", title: "Curtain Call", masterPageType: "Finale Room", mediaType: "Image", transition: "Fade", subtitle: "Close the performance journey.", narration: "The performance ends, but the cultural memory continues with the audience.", description: "Performance journey finale.", mainMediaUrl: "https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?auto=format&fit=crop&w=1600&q=80", altText: "Audience and stage lights", transcript: "The performance ends, but the cultural memory continues with the audience.", finaleConfig: { achievementTitle: "Performance Witness", completionMessage: "You completed the Living Performance Journey.", primaryCtaLabel: "Replay Performance", primaryCtaRoute: "performance-welcome" } }
    ]
  },
  {
    presetId: "school-field-trip",
    presetName: "School Field Trip Builder",
    museumName: "Learning Field Trip Museum",
    museumSlug: "learning-field-trip-museum",
    tenantTheme: "Education-first guided visit",
    walkthroughKey: "Walkthrough1",
    globalSettings: { experienceStyle: "Educational", colorPalette: ["Blue", "White", "Yellow"], transitionType: "Fade", accessibilityEnabled: true, reducedMotionSupport: true, calmMode: true },
    rooms: [
      { order: 1, roomKey: "fieldtrip-welcome", title: "Class Visit Briefing", masterPageType: "Onboarding Guide", mediaType: "Image", transition: "Fade", subtitle: "Orient students before the visit begins.", narration: "Welcome, learners. Today you will observe, compare, and reflect like museum researchers.", description: "Student-oriented onboarding room.", mainMediaUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1600&q=80", altText: "Students in a classroom", transcript: "Welcome, learners. Today you will observe, compare, and reflect like museum researchers.", onboardingConfig: { guideName: "Learning Guide", introText: "Observe, compare, and reflect.", visitorChoices: [{ label: "Start Learning", nextRoomId: "fieldtrip-timeline", description: "Begin the learning route." }] } },
      { order: 2, roomKey: "fieldtrip-timeline", title: "Big Idea Timeline", masterPageType: "Timeline Room", mediaType: "Image", transition: "Fade", subtitle: "Understand the subject through key moments.", narration: "A timeline helps us connect individual objects to wider changes in society.", description: "Educational timeline room.", mainMediaUrl: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=1600&q=80", altText: "Open books in a library", transcript: "A timeline helps us connect individual objects to wider changes in society.", nextRoomId: "fieldtrip-observe" },
      { order: 3, roomKey: "fieldtrip-observe", title: "Observe Like a Curator", masterPageType: "Artifact Exploration Room", mediaType: "Image", transition: "Cinematic Zoom", subtitle: "Practice close-looking skills.", narration: "Start with what you can see. Then ask what it means and who made it.", description: "Close-looking artifact activity.", mainMediaUrl: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1600&q=80", altText: "Books and study table", transcript: "Start with what you can see. Then ask what it means and who made it.", nextRoomId: "fieldtrip-quiz", hotspots: [{ label: "Look", title: "What do you notice?", description: "Record visible details before interpreting." }, { label: "Wonder", title: "What do you wonder?", description: "Turn observation into a question." }] },
      { order: 4, roomKey: "fieldtrip-quiz", title: "Reflection Choice", masterPageType: "Branching Choice Room", mediaType: "Image", transition: "Fade", subtitle: "Choose your learning reflection.", narration: "Select the reflection that best matches what you discovered.", description: "Simple branching reflection room.", mainMediaUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1600&q=80", altText: "Laptop with learning notes", transcript: "Select the reflection that best matches what you discovered.", visitorChoices: [{ label: "I found a pattern", nextRoomId: "fieldtrip-finale", description: "Reflect on repeated ideas." }, { label: "I found a question", nextRoomId: "fieldtrip-finale", description: "Reflect on open inquiry." }] },
      { order: 5, roomKey: "fieldtrip-finale", title: "Field Trip Complete", masterPageType: "Finale Room", mediaType: "Image", transition: "Fade", subtitle: "Close with learning outcomes.", narration: "You completed the field trip route. Bring your notes into discussion.", description: "Educational finale room.", mainMediaUrl: "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1600&q=80", altText: "Graduation caps in the air", transcript: "You completed the field trip route. Bring your notes into discussion.", finaleConfig: { achievementTitle: "Field Trip Complete", completionMessage: "You completed the School Field Trip Builder preset.", primaryCtaLabel: "Replay Lesson", primaryCtaRoute: "fieldtrip-welcome" } }
    ]
  },
  {
    presetId: "vip-preview-experience",
    presetName: "VIP Preview Experience",
    museumName: "VIP Preview Museum",
    museumSlug: "vip-preview-museum",
    tenantTheme: "Premium donor and partner preview",
    walkthroughKey: "Walkthrough1",
    globalSettings: { experienceStyle: "Premium", colorPalette: ["Black", "Champagne", "Ivory"], transitionType: "Fade", accessibilityEnabled: true, reducedMotionSupport: true, calmMode: true },
    rooms: [
      { order: 1, roomKey: "vip-arrival", title: "Private Arrival", masterPageType: "Onboarding Guide", mediaType: "Image", transition: "Fade", subtitle: "Welcome partners, donors, and preview guests.", narration: "Welcome to a private preview designed to introduce the museum vision, collection value, and partnership opportunities.", description: "Premium preview onboarding.", mainMediaUrl: "https://images.unsplash.com/photo-1519167758481-83f29c8cf6d8?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1519167758481-83f29c8cf6d8?auto=format&fit=crop&w=1600&q=80", altText: "Elegant event hall", transcript: "Welcome to a private preview designed to introduce the museum vision, collection value, and partnership opportunities.", onboardingConfig: { guideName: "Preview Host", introText: "Enter a concise premium preview.", visitorChoices: [{ label: "Begin Preview", nextRoomId: "vip-vision", description: "Start the VIP route." }] } },
      { order: 2, roomKey: "vip-vision", title: "The Museum Vision", masterPageType: "Cinematic Walkthrough Exhibition", mediaType: "Image", transition: "Fade", subtitle: "Present the institution’s purpose and audience value.", narration: "A strong museum experience connects mission, collection, learning, and public value into one coherent visitor journey.", description: "Vision presentation room.", mainMediaUrl: "https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=1600&q=80", altText: "Museum interior with dramatic lighting", transcript: "A strong museum experience connects mission, collection, learning, and public value into one coherent visitor journey.", nextRoomId: "vip-featured-object" },
      { order: 3, roomKey: "vip-featured-object", title: "Featured Collection Moment", masterPageType: "Artifact Exploration Room", mediaType: "Image", transition: "Cinematic Zoom", subtitle: "Showcase one high-value interpretive object.", narration: "A featured object can anchor a larger story and demonstrate why the collection matters.", description: "VIP artifact showcase room.", mainMediaUrl: "https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=1600&q=80", altText: "Featured artifact in a museum display", transcript: "A featured object can anchor a larger story and demonstrate why the collection matters.", nextRoomId: "vip-finale", hotspots: [{ label: "Impact", title: "Interpretive impact", description: "Why this object matters to visitors and partners." }] },
      { order: 4, roomKey: "vip-finale", title: "Partner Next Steps", masterPageType: "Finale Room", mediaType: "Image", transition: "Fade", subtitle: "Close with partnership and ticket pathways.", narration: "Thank you for previewing the experience. The next step is to choose how you would like to support, visit, or partner.", description: "VIP partner finale room.", mainMediaUrl: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1600&q=80", backgroundMediaUrl: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1600&q=80", altText: "Formal event setting", transcript: "Thank you for previewing the experience. The next step is to choose how you would like to support, visit, or partner.", finaleConfig: { achievementTitle: "VIP Preview Complete", completionMessage: "You completed the VIP Preview Experience.", primaryCtaLabel: "Contact Team", primaryCtaRoute: "contact", secondaryCtaLabel: "View Tickets", secondaryCtaRoute: "tickets" } }
    ]
  }
];

export const MUSEUM_PRESETS = [SENTIENT_ARCHIVE_PRESET, ...MIXED_EXPERIENCE_PRESETS];