-- Cleanup seeded/demo commerce data before connecting Stripe.
-- Run this ONE file in the Supabase SQL Editor. Idempotent (safe to run twice).
--
-- Background: seedScaverseCivilization seeded three fictional demo museums
-- (National Heritage Museum, Future Science Dome, Living Arts Gallery —
-- tenant_ids 6a22c77fceb3a375126ca3a6/a7/a8) with fake ticket types, ticket
-- orders ("visitor.demo@scaverse.demo", seed_key='order_*'/'ticket_*') and
-- analytics events tagged event_data->>'source' = 'seed'. Separately,
-- seedMuseumGradeContent wrote demo tickets (demo-ticket-N@example.com) and
-- demo vendors (demo-vendor-N@example.com) onto the real Asian Operatic
-- Museum tenant. A recent re-import brought all of this back. None of it is
-- real revenue and it must not get mixed with live Stripe payments.
--
-- Order matters (children before parents):
--   1. tickets            (visitor-facing ticket records)
--   2. ticket_orders      (the fake orders — seed_key / demo emails)
--   3. ticket_types       (demo-only ticket type definitions, by tenant)
--   4. analytics_events   (events generated by the seeded demo museums)
--   5. vendors            (demo vendors reset to pending, not deleted)

BEGIN;

-- 1. Delete fake tickets (public.tickets) — demo visitor emails from
--    seedMuseumGradeContent (demo-ticket-N@example.com) and
--    seedScaverseCivilization (visitor.demo@scaverse.demo)
DELETE FROM public.tickets
WHERE visitor_email ILIKE '%@scaverse.demo'
   OR visitor_email ILIKE '%@example.com';

-- 2. Delete fake ticket orders — tagged with a seed_key, or demo visitor emails
DELETE FROM public.ticket_orders
WHERE (seed_key IS NOT NULL AND seed_key <> '')
   OR visitor_email ILIKE '%@scaverse.demo'
   OR visitor_email ILIKE '%@example.com';

-- 3. Delete demo-only ticket types belonging to the three fictional seed
--    museums. Real Asian Operatic Museum ticket types (a different tenant_id)
--    are untouched, even if some of them carry a leftover seed_key.
DELETE FROM public.ticket_types
WHERE tenant_id IN (
  '6a22c77fceb3a375126ca3a6', -- National Heritage Museum (seed)
  '6a22c77fceb3a375126ca3a7', -- Future Science Dome (seed)
  '6a22c77fceb3a375126ca3a8'  -- Living Arts Gallery (seed)
);

-- 4. Purge analytics events generated for the fictional seed museums
--    (explicitly tagged event_data->>'source' = 'seed'). This zeroes out
--    the fake purchase/visit activity behind the inflated revenue charts.
DELETE FROM public.analytics_events
WHERE event_data->>'source' = 'seed';

-- 5. Demo vendors (@example.com): reset from approved back to pending instead
--    of deleting, so they no longer appear as live partners but the
--    application record/history is preserved.
UPDATE public.vendors
SET status = 'pending'
WHERE email ILIKE '%@example.com'
  AND status = 'approved';

COMMIT;

-- ---------------------------------------------------------------------------
-- Verification — run these after COMMIT and post the results:
-- ---------------------------------------------------------------------------
-- Should return 0:
-- SELECT count(*) AS fake_orders FROM public.ticket_orders
--   WHERE (seed_key IS NOT NULL AND seed_key <> '')
--      OR visitor_email ILIKE '%@scaverse.demo' OR visitor_email ILIKE '%@example.com';
--
-- Should return 0:
-- SELECT count(*) AS fake_tickets FROM public.tickets
--   WHERE visitor_email ILIKE '%@scaverse.demo' OR visitor_email ILIKE '%@example.com';
--
-- Should return 0:
-- SELECT coalesce(sum(total_price), 0) AS total_revenue FROM public.ticket_orders;
--
-- Should return 0:
-- SELECT count(*) FROM public.analytics_events WHERE event_data->>'source' = 'seed';
--
-- Manual review — remaining ticket types (confirm each is a real, sellable type):
-- SELECT id, tenant_id, ticket_name, ticket_type, price, status, seed_key FROM public.ticket_types ORDER BY tenant_id, ticket_name;
--
-- Confirm no demo vendors remain approved:
-- SELECT business_name, email, status FROM public.vendors WHERE email ILIKE '%@example.com';
