import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

const now = () => new Date().toISOString();
const img = (id) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=80`;
const MEDIA = 'https://cdn.scaverse.demo/media';
const AUDIO = 'https://cdn.scaverse.demo/audio';
const VIDEO = 'https://cdn.scaverse.demo/videos';

const tenantSeeds = [
  ['tenant_national_heritage','National Heritage Museum','national-heritage','Walk through memory, trade, family, and nationhood.','A warm digital museum about national memory, old trade routes, family archives, oral histories, festivals, and civic identity.','#7A4A24','#E8D2A0','#D9A441','#1F130A','Singapore Civic District','hello@nationalheritage.demo',img('photo-1566127992631-137a642a90f4')],
  ['tenant_future_science','Future Science Dome','future-science-dome','Step into tomorrow before it arrives.','A futuristic science museum about AI, robotics, medicine, climate systems, space exploration, quantum computing, and future transport.','#0B1026','#6FE7FF','#4A7DFF','#050816','One North Innovation District','hello@futurescience.demo',img('photo-1451187580459-43490279c0fa')],
  ['tenant_living_arts','Living Arts Gallery','living-arts-gallery','Where art moves, speaks, reacts, and remembers.','A contemporary gallery for motion sculpture, video performance, sound rooms, light installations, digital portraits, and living archives.','#0D0D0D','#F4EDE4','#FF4FD8','#050505','Gillman Barracks Arts Cluster','hello@livingarts.demo',img('photo-1547891654-e66ed7ebb968')]
];

const users = [
  ['usr_master_admin_001','master.admin@scaverse.demo','Amelia Tan','Amelia','master_admin','global',null,'SCAVerse Master Platform Owner'],
  ['usr_platform_admin_001','platform.admin@scaverse.demo','Daniel Koh','Daniel','platform_admin','platform',null,'Platform Operations Admin'],
  ['usr_tenant_admin_heritage_001','heritage.admin@scaverse.demo','Nur Aisyah Rahman','Aisyah','tenant_admin','tenant','tenant_national_heritage','Digital Heritage Curator'],
  ['usr_tenant_admin_science_001','science.admin@scaverse.demo','Dr. Marcus Lee','Marcus','tenant_admin','tenant','tenant_future_science','Science Experience Director'],
  ['usr_tenant_admin_arts_001','arts.admin@scaverse.demo','Mei Lin Ong','Mei Lin','tenant_admin','tenant','tenant_living_arts','Contemporary Arts Producer'],
  ['usr_official_tester_001','official.tester@scaverse.demo','Ravi Menon','Ravi','official_tester','test',null,'Official Platform Tester'],
  ['usr_visitor_001','visitor.demo@scaverse.demo','Clara Lim','Clara','visitor','public',null,'Museum Visitor']
];

const roomSeeds = {
  tenant_national_heritage: [
    ['room_heritage_entrance','heritage-entrance-hall','Entrance Hall of Memory','A warm opening room with maps, portraits, and a central archive desk.',img('photo-1566127992631-137a642a90f4'),'heritage-soft-hall.mp3','entrance',1,'warm archive glow','calm, respectful, historical','Start here. Click the highlighted map, desk, or portrait to begin.'],
    ['room_heritage_trade','maritime-trade-gallery','Maritime Trade Gallery','A room about ships, port life, old trade routes, and objects carried across seas.',img('photo-1500530855697-b586d89ba3ee'),'harbour-memory.mp3','gallery',2,'gold wall wash','exploratory','Look for the compass, map, and ship ledger.'],
    ['room_heritage_family','family-archive-room','Family Archive Room','A quieter room filled with photographs, letters, household objects, and oral stories.',img('photo-1494526585095-c41746248156'),'family-archive.mp3','archive',3,'soft table lamp','personal, emotional, intimate','Click the cabinet, letters, and listening station.'],
    ['room_heritage_completion','heritage-reflection-room','Reflection Room','The final room where visitors review the journey and continue to tickets or shop.',img('photo-1507842217343-583bb7270b66'),'reflection-room.mp3','completion',4,'quiet golden fade','reflective','You have reached the end. Choose what to do next.']
  ],
  tenant_future_science: [
    ['room_science_launch','dome-launch-bay','Dome Launch Bay','A glowing entry space where visitors begin their future science mission.',img('photo-1451187580459-43490279c0fa'),'science-launch.mp3','entrance',1,'blue neon grid','futuristic, energetic','Click the AI console to begin your mission.'],
    ['room_science_ai_lab','ai-robotics-lab','AI and Robotics Lab','A room filled with machines, robotics arms, sensors, and AI interfaces.',img('photo-1518770660439-4636190af475'),'robotics-lab.mp3','immersive',2,'cool blue lab panels','technical, curious','Click the robot arm, AI console, and sensor wall.'],
    ['room_science_space','space-habitat-zone','Space Habitat Zone','A future room about Mars habitats, deep space signals, and survival beyond Earth.',img('photo-1446776811953-b23d57bd21aa'),'space-habitat.mp3','gallery',3,'star field reflection','vast, ambitious','Click the habitat model, signal wall, and transport capsule.'],
    ['room_science_future_complete','future-mission-complete','Future Mission Complete','A final room that summarizes the scientific ideas explored by the visitor.',img('photo-1454789548928-9efd52dc4031'),'future-complete.mp3','completion',4,'bright horizon glow','hopeful, expansive','Review your mission and choose your next step.']
  ],
  tenant_living_arts: [
    ['room_arts_threshold','gallery-threshold','Gallery Threshold','A dark entry room with soft light, moving shadows, and the first artwork signal.',img('photo-1547891654-e66ed7ebb968'),'gallery-threshold.mp3','entrance',1,'soft gallery spotlight','quiet, stylish, expectant','Click the moving light piece to enter the gallery.'],
    ['room_arts_motion','motion-sculpture-room','Motion Sculpture Room','A room for sculptures, shadows, projected movement, and body-based art.',img('photo-1500530855697-b586d89ba3ee'),'motion-room.mp3','immersive',2,'moving spotlights','alive, experimental','Click the sculpture, shadow screen, and floor projection.'],
    ['room_arts_video','video-performance-chamber','Video Performance Chamber','A media room with video loops, sound work, and digital portraits.',img('photo-1518005020951-eccb494ad742'),'video-chamber.mp3','gallery',3,'screen glow','media-heavy, reflective','Click the video wall, portrait grid, and sound archive.'],
    ['room_arts_afterglow','afterglow-room','Afterglow Room','A final quiet room where visitors can replay works, buy prints, or book events.',img('photo-1524230572899-a752b3835840'),'afterglow.mp3','completion',4,'pink fade and cream wall','soft, final, lingering','End your visit or continue into events and shop.']
  ]
};

const heritageExhibits = [
 ['exh_heritage_trade_map','room_heritage_trade','Ancient Trade Map','A map showing old sea routes and goods moving through the region.','This map helps visitors understand how trade shaped food, language, settlement, and culture.','Map',94,true,img('photo-1524661135-423995f22d0b')],
 ['exh_heritage_documents','room_heritage_entrance','Founding Documents','A document set showing how civic memory becomes official record.','These documents show how speeches, letters, agreements, and public records become part of a nation\'s memory.','Document',91,true,img('photo-1450101499163-c8848c66ca85')],
 ['exh_heritage_compass','room_heritage_trade','Maritime Route Compass','A compass used to explain navigation and sea journeys.','The compass represents courage, risk, trade, and navigation.','Navigation',86,false,img('photo-1500530855697-b586d89ba3ee')],
 ['exh_heritage_oral_station','room_heritage_family','Oral History Listening Station','A listening post with short memories from elders and families.','This station contains voices from people who remember old streets, schools, markets, food, and family routines.','Audio Archive',96,true,img('photo-1493246507139-91e8fad9978e')],
 ['exh_heritage_war_wall','room_heritage_entrance','War Memory Wall','A wall of names, photographs, and difficult memories.','This wall helps visitors understand how conflict affects ordinary people, families, food supply, and public safety.','Memory Wall',89,false,img('photo-1519681393784-d120267933ba')],
 ['exh_heritage_garments','room_heritage_family','Festival Garment Collection','Clothing worn during festivals, family events, and public celebrations.','The garment collection shows how fabric, colour, and form carry meaning during celebrations.','Textile',84,false,img('photo-1496747611176-843222e1e57c')],
 ['exh_heritage_city_model','room_heritage_entrance','Old City Street Model','A small model of streets, shops, homes, and community life.','This street model helps visitors see how people lived, worked, moved, and gathered before today’s city shape.','Model',82,false,img('photo-1518005020951-eccb494ad742')],
 ['exh_heritage_family_cabinet','room_heritage_family','Family Archive Cabinet','A cabinet of letters, photographs, receipts, and small keepsakes.','The cabinet shows how private homes become small museums of memory.','Family Archive',93,true,img('photo-1494526585095-c41746248156')]
];
const scienceTitles = [['exh_science_ai_console','AI Vision Console','room_science_ai_lab','A console showing how machines learn from images, patterns, and signals.'],['exh_science_mars_habitat','Mars Habitat Model','room_science_space','A model showing how humans may live safely on Mars.'],['exh_science_nanobot','Medical Nanobot Display','room_science_ai_lab','A simple exhibit explaining tiny medical machines inside the body.'],['exh_science_quantum_core','Quantum Computing Core','room_science_ai_lab','A visual model explaining quantum computing in simple terms.'],['exh_science_robot_arm','Robotics Arm Lab','room_science_ai_lab','A robotic arm exhibit about precision, automation, and care work.'],['exh_science_signal_wall','Deep Space Signal Wall','room_science_space','A wall showing signals, distance, stars, and communication.'],['exh_science_climate','Climate Simulator','room_science_launch','A simulation showing heat, water, city design, and climate risk.'],['exh_science_transport','Future Transport Capsule','room_science_space','A capsule showing how future travel may become cleaner and faster.']];
const artsTitles = [['exh_arts_motion_sculpture','Motion Sculpture','room_arts_motion','A sculpture that appears to change as visitors move around it.'],['exh_arts_light_room','Light Room Installation','room_arts_threshold','A room of shifting light, reflection, and soft colour.'],['exh_arts_protest_wall','Protest Poster Wall','room_arts_video','A wall of posters about voice, protest, and public feeling.'],['exh_arts_soundwave','Soundwave Archive','room_arts_video','A sound artwork built from voice, rhythm, and memory.'],['exh_arts_video_loop','Video Performance Loop','room_arts_video','A looping performance video about body, space, and repetition.'],['exh_arts_textile_field','Textile Memory Field','room_arts_motion','A fabric installation about memory, labour, and touch.'],['exh_arts_portrait_grid','Digital Portrait Grid','room_arts_video','A digital portrait wall that presents many faces as one archive.'],['exh_arts_shadow_stage','Interactive Shadow Stage','room_arts_motion','A floor and wall installation where visitor shadows become part of the work.']];

const artifactLists = {
 tenant_national_heritage: [
  ['art_heritage_trade_map_wall','room_heritage_trade','exh_heritage_trade_map','Ancient Trade Map',58,34,21,15,'wall'],['art_heritage_compass_floor','room_heritage_trade','exh_heritage_compass','Route Compass',42,77,13,16,'floor'],['art_heritage_documents_table','room_heritage_entrance','exh_heritage_documents','Founding Documents',49,69,18,12,'table'],['art_heritage_oral_station','room_heritage_family','exh_heritage_oral_station','Oral History Listening Station',64,70,16,18,'floor'],['art_heritage_war_wall','room_heritage_entrance','exh_heritage_war_wall','War Memory Wall',25,32,24,17,'wall'],['art_heritage_garment_display','room_heritage_family','exh_heritage_garments','Festival Garment Display',36,65,15,24,'floor'],['art_heritage_city_model','room_heritage_entrance','exh_heritage_city_model','Old City Street Model',58,74,22,17,'floor'],['art_heritage_family_cabinet','room_heritage_family','exh_heritage_family_cabinet','Family Archive Cabinet',27,61,18,27,'floor'],['art_heritage_audio_label','room_heritage_family',null,'Listen to Memory',74,27,12,9,'floating'],['art_heritage_exit_card','room_heritage_completion',null,'Continue the Journey',50,58,24,16,'floating'],['art_heritage_ticket_prompt','room_heritage_completion',null,'Book a Guided Walk',35,76,18,12,'floor'],['art_heritage_shop_prompt','room_heritage_completion',null,'Visit the Heritage Shop',65,76,18,12,'floor']
 ],
 tenant_future_science: [['art_science_ai_console','room_science_ai_lab','exh_science_ai_console','AI Vision Console',48,56,22,18,'table'],['art_science_robot_arm','room_science_ai_lab','exh_science_robot_arm','Robotics Arm Lab',72,67,17,25,'floor'],['art_science_nanobot','room_science_ai_lab','exh_science_nanobot','Medical Nanobot Display',30,60,16,18,'table'],['art_science_quantum_core','room_science_ai_lab','exh_science_quantum_core','Quantum Computing Core',54,74,18,20,'floor'],['art_science_climate','room_science_launch','exh_science_climate','Climate Simulator',61,58,21,17,'table'],['art_science_mission_panel','room_science_launch',null,'Mission Start Panel',50,33,28,16,'wall'],['art_science_mars_habitat','room_science_space','exh_science_mars_habitat','Mars Habitat Model',39,72,20,18,'floor'],['art_science_signal_wall','room_science_space','exh_science_signal_wall','Deep Space Signal Wall',66,31,24,18,'wall'],['art_science_transport','room_science_space','exh_science_transport','Future Transport Capsule',58,76,22,18,'floor'],['art_science_completion_card','room_science_future_complete',null,'Mission Complete Card',50,49,28,18,'floating'],['art_science_lab_ticket','room_science_future_complete',null,'Book Lab Simulation Pass',36,75,20,13,'floor'],['art_science_shop','room_science_future_complete',null,'Explore Science Kits',65,75,20,13,'floor']],
 tenant_living_arts: [['art_arts_light_room','room_arts_threshold','exh_arts_light_room','Light Room Installation',50,38,28,20,'wall'],['art_arts_entry_signal','room_arts_threshold',null,'First Signal',50,70,18,15,'floor'],['art_arts_motion_sculpture','room_arts_motion','exh_arts_motion_sculpture','Motion Sculpture',45,68,18,24,'floor'],['art_arts_shadow_stage','room_arts_motion','exh_arts_shadow_stage','Interactive Shadow Stage',64,72,22,16,'floor'],['art_arts_textile_field','room_arts_motion','exh_arts_textile_field','Textile Memory Field',28,63,17,22,'floor'],['art_arts_video_loop','room_arts_video','exh_arts_video_loop','Video Performance Loop',52,34,30,18,'wall'],['art_arts_portrait_grid','room_arts_video','exh_arts_portrait_grid','Digital Portrait Grid',25,32,22,18,'wall'],['art_arts_soundwave','room_arts_video','exh_arts_soundwave','Soundwave Archive',73,62,16,18,'table'],['art_arts_protest_wall','room_arts_video','exh_arts_protest_wall','Protest Poster Wall',39,29,22,16,'wall'],['art_arts_afterglow_card','room_arts_afterglow',null,'Afterglow Reflection',50,50,28,18,'floating'],['art_arts_event_ticket','room_arts_afterglow',null,'Book Evening Performance',35,75,20,13,'floor'],['art_arts_print_shop','room_arts_afterglow',null,'Buy Limited Art Prints',65,75,20,13,'floor']]
};

const vendorSeeds = {
 tenant_national_heritage: [['vendor_heritage_kopi_archive','Kopi Archive Cart','food_beverage','approved','Traditional drinks and snacks inspired by old coffee shops.'],['vendor_heritage_book_room','The Heritage Book Room','merchandise','approved','Books, postcards, and local memory publications.'],['vendor_heritage_craft_house','Craft House SG','cultural_arts','pending','Handmade crafts based on festival and family traditions.'],['vendor_heritage_print_shop','Old Street Print Shop','merchandise','approved','Archive-style prints of maps, streets, and buildings.'],['vendor_heritage_school_kits','Young Archivist Kits','education','approved','Learning packs for students and school visits.'],['vendor_heritage_rejected','Unverified Antique Dealer','merchandise','rejected','Rejected because provenance documents were incomplete.']],
 tenant_future_science: [['vendor_science_robot_kits','RoboKit Lab','technology','approved','Beginner robotics kits for children and families.'],['vendor_science_space_food','Space Snack Bar','food_beverage','approved','Fun science-themed snacks and drinks.'],['vendor_science_books','Tomorrow Books','education','approved','Popular science books and STEM guides.'],['vendor_science_vr','Mini VR Worlds','education','pending','Short VR learning stations for future science topics.'],['vendor_science_models','Future Model Studio','merchandise','approved','Mars habitat models, AI badges, and dome collectibles.'],['vendor_science_suspended','Unsafe Battery Toys','technology','suspended','Suspended due to safety documentation issues.']],
 tenant_living_arts: [['vendor_arts_prints','Afterglow Prints','merchandise','approved','Limited prints from gallery artists.'],['vendor_arts_zines','Small Press Table','merchandise','approved','Artist books, zines, and essays.'],['vendor_arts_sound','Sound Objects','merchandise','pending','Small sound-based artwork objects.'],['vendor_arts_textile','Textile Memory Studio','cultural_arts','approved','Fabric pieces and hand-sewn gallery goods.'],['vendor_arts_cafe','Black Box Cafe','food_beverage','approved','Gallery cafe with simple food and drinks.'],['vendor_arts_rejected','Unlicensed Poster Seller','merchandise','rejected','Rejected because print rights were not confirmed.']]
};

const ticketNames = {
 tenant_national_heritage: [['ticket_heritage_adult','Adult General Admission',18],['ticket_heritage_student','Student Pass',9],['ticket_heritage_family','Family Bundle',48],['ticket_heritage_virtual','Virtual Tour Access',6],['ticket_heritage_guided_walk','Heritage Guided Walk',35]],
 tenant_future_science: [['ticket_science_adult','Adult Dome Admission',24],['ticket_science_student','Student Future Pass',12],['ticket_science_family','Family Science Bundle',68],['ticket_science_virtual','Virtual Lab Access',9],['ticket_science_lab','Lab Simulation Pass',42]],
 tenant_living_arts: [['ticket_arts_admission','Gallery Admission',16],['ticket_arts_student','Student Arts Pass',8],['ticket_arts_family','Family Gallery Bundle',44],['ticket_arts_digital','Digital Exhibition Pass',7],['ticket_arts_evening','Evening Performance Pass',38]]
};
const productNames = {
 tenant_national_heritage: ['Ancient Trade Map Poster','Family Archive Notebook','Heritage Tote Bag','Oral History Audio Download','Festival Garment Postcard Set','Old City Model Mini Print','Young Archivist Student Kit','Heritage Guided Walk Voucher'],
 tenant_future_science: ['AI Console Sticker Pack','Mars Habitat Model Kit','Robotics Arm Mini Kit','Climate Simulator Workbook','Quantum Core Poster','Deep Space Signal Hoodie','Future Transport Capsule Toy','Virtual Lab Replay Pass'],
 tenant_living_arts: ['Motion Sculpture Art Print','Light Room Postcard Pack','Soundwave Archive Download','Video Performance Digital Pass','Textile Memory Patch','Digital Portrait Poster','Interactive Shadow Stage Ticket','Afterglow Gallery Tote']
};

const qaFirst = [
 ['qa_001_base44_dependency','Base44 dependency remains in 87 files','Base44 dependency','critical','/platform/admin'],['qa_002_floor_detection_heuristic','Museum Mode floor detection is heuristic, not true semantic AI','Museum Mode placement','major','/museum/:tenantSlug/admin/walkthrough'],['qa_003_tenant_direct_url','Tenant admin direct URL access must be RLS tested','tenant isolation','critical','/museum/future-science-dome/admin'],['qa_004_ticket_checkout','Ticket checkout requires Stripe end-to-end proof','ticket checkout','major','/museum/:tenantSlug/tickets'],['qa_005_vendor_spam','Public vendor form requires spam protection','vendor approval','warning','/museum/:tenantSlug/vendors']
];
const qaRest = [['Media uploads require MIME and size validation','media upload','major'],['Mobile artifact drag handles need stronger touch controls','mobile layout','major'],['AI guide must not expose tenant-private data','authentication','critical'],['Analytics events need tenant-scoped validation','analytics tracking','major'],['Supabase storage bucket policies require production test','Supabase migration','critical'],['Visitor role can see only public routes','authentication','major'],['Official tester access needs gated route proof','authentication','warning'],['Platform admin must not accidentally edit tenant data without explicit context','admin publishing','major'],['Museum Mode undo redo is missing','Museum Mode placement','warning'],['Artifact video panel needs mobile responsiveness testing','mobile layout','warning'],['Room background images need fallback states','media upload','minor'],['Music autoplay rules must respect browser restrictions','music','warning'],['AI guide fallback response must be simple and safe','AI guide','warning'],['Ticket availability must decrease after purchase','ticket checkout','major'],['Refunded ticket must not allow check-in','ticket checkout','major'],['Vendor rejected state must hide public booth','vendor approval','warning'],['Commerce products need stock depletion test','commerce','warning'],['Public museum home needs empty-state fallback','routing','minor'],['Route redirects from legacy admin paths require proof','routing','warning'],['QA Sentinel issue screenshots must load reliably','QA Sentinel','minor'],['QA Sentinel severity filters need test data','QA Sentinel','minor'],['Analytics dashboard should distinguish visitors from admins','analytics tracking','warning'],['Museum page draft state must hide from public','admin publishing','major'],['Tenant media library must not leak cross-tenant files','tenant isolation','critical'],['Platform media registry needs approved and unapproved examples','media registry','minor'],['Master prompt versions need rollback metadata','master prompts','warning'],['Onboarding completion state must persist','onboarding','minor'],['Accessibility mode requires text contrast validation','accessibility','major'],['Keyboard navigation for artifact panels is incomplete','accessibility','major'],['Visitor completion page needs next action tracking','analytics tracking','minor'],['Walkthrough room order must be deterministic','walkthrough','warning'],['Duplicate tenant slug should be blocked','tenant management','critical'],['Inactive tenant should not expose public museum route','tenant management','critical'],['Seed script must be idempotent','database seeding','critical'],['Migration tracker must show Base44 to Supabase progress','Supabase migration','warning']];

async function clearSeeded(base44, name, predicate) {
  const api = base44.asServiceRole.entities[name];
  if (!api) return 0;
  const rows = await api.list('-created_date', 1000);
  let count = 0;
  for (const row of rows || []) if (predicate(row)) { await api.delete(row.id); count++; }
  return count;
}
async function bulk(base44, name, rows) {
  if (!rows.length) return 0;
  const api = base44.asServiceRole.entities[name];
  await api.bulkCreate(rows);
  return rows.length;
}
function makeRoom(r, tenantId, artifactsByRoom, layout) {
  const sprites = (artifactsByRoom[r[0]] || []).map(a => ({ id:a.seed_key, title:a.artifact_title, header:a.artifact_header, description:a.artifact_description, body:a.artifact_body, media_url:a.sprite_image_url, video_url:a.video_url, x:a.x_position_percent, y:a.y_position_percent, width:a.width_percent, height:a.height_percent, rotation:a.rotation_degrees, depth:a.z_index, locked:false, display_mode:'click', floor_locked:a.placement_type==='floor' }));
  return { id:r[0], tenant_id:tenantId, room_key:r[1], title:r[2], description:r[3], narration:r[3], media_url:r[4], media_type:'image', background_media_url:r[4], background_media_type:'image', audio_url:`${AUDIO}/${r[5]}`, audio_type:'audio', page_type:r[6]==='completion'?'finale_room':r[6]==='archive'?'archive_room':r[6]==='entrance'?'onboarding_guide':'walkthrough_exhibition', order:r[7], visibility:'published', lighting:r[8], mood:r[9], visitor_instruction:r[10], museum_mode_enabled:true, artifact_placement_enabled:true, room_semantic_layout: layout, artifact_sprites:sprites, accessibility:{alt_text:r[2], transcript:r[3], sensory_warning:''}, hotspots:sprites.slice(0,3).map(s=>({id:`hotspot_${s.id}`, label:s.title, title:s.title, description:s.description, x:s.x, y:s.y})), finale_config:{achievement_title:r[2], completion_message:r[3], next_ctas:[]}, onboarding_config:{guide_name:'Museum Guide', intro_text:r[3], step_instruction:r[10], choices:[]} };
}
function pageRecords(seed, tid) {
  const [legacy,name,slug,tagline,desc,,,,,,email,cover] = seed;
  const keys = [['museum_home','home'],['museum','about'],['tickets','tickets'],['walkthrough','walkthrough'],['walkthrough','begin-tour'],['ai_guide','guide'],['vendors','vendors'],['commerce','commerce'],['completion','completion']];
  return keys.map(([pageKey, plain], i) => ({ tenantId:tid, museumId:tid, tenantSlug:slug, pageKey, pageName:`${name} ${plain}`, pageTitle: plain==='home'?`${name} Home`:`${name} ${plain}`, pageContent:desc, ownershipScope:'museum', publishState:'published', visibilityState:'public', publishedVersion:1, draftVersion:1, heroMedia:{fileUrl:cover}, sections:[{sectionKey:'hero', title: plain==='home'?tagline:`${name} ${plain}`, subtitle:desc, description:desc},{sectionKey:'body', title:'A living museum experience', description:'Explore rooms, artifacts, tickets, vendors, commerce, and AI guide content created from the SCAVerse seed universe.'}], ctaSlots:[{ctaKey:`${plain}_cta`, label: plain==='home'?'Start Tour':'Open', route:`/museum/${slug}/${plain==='walkthrough'?'begin-tour':plain}`}], seo:{title:`${name} ${plain}`, description:desc}, canonicalRoute:`/museum/${slug}/${plain}` }));
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error:'Unauthorized' }, { status:401 });

    const seedTenantKeys = tenantSeeds.map(t=>t[0]);
    const seedSlugs = tenantSeeds.map(t=>t[2]);
    const report = { inspected:['MuseumTenant','ExperienceConfig','MuseumPageConfig','Exhibit','Vendor','TicketType','CommerceProduct','MuseumModeArtifact','RoomSemanticLayout','QASentinelIssue','RouteCoverage','RolePermission','TenantAccess','ModuleConfig','AIGuideConfig','AIGuideQA','MasterPrompt','PromptVersion','MigrationTracker','AnalyticsEvent','MusicAsset','TenantMedia','OnboardingStep','TicketOrder'], seeded:{}, created:['UserProfile','TicketType','CommerceProduct','MuseumModeArtifact','RoomSemanticLayout','RouteCoverage','RolePermission','TenantAccess','AIGuideConfig','AIGuideQA','MigrationTracker','OnboardingStep','TicketOrder'], mappings:['tenant status active → live','page_key home → MuseumPageConfig.pageKey museum_home','route begin-tour → walkthrough renderer route','QA high/medium/low → major/warning/minor','seed tenant IDs → real Base44 tenant_id at runtime'] };

    const customSeedEntities = ['UserProfile','TicketType','CommerceProduct','MuseumModeArtifact','RoomSemanticLayout','RouteCoverage','RolePermission','TenantAccess','AIGuideConfig','AIGuideQA','MigrationTracker','OnboardingStep','TicketOrder'];
    for (const entity of customSeedEntities) await clearSeeded(base44, entity, r => String(r.seed_key || '').startsWith('seed_') || String(r.seed_key || '').startsWith('usr_') || String(r.seed_key || '').startsWith('ticket_') || String(r.seed_key || '').startsWith('art_') || String(r.seed_key || '').startsWith('route_') || String(r.seed_key || '').startsWith('mig_'));
    await clearSeeded(base44, 'MuseumTenant', r => seedSlugs.includes(r.slug));
    await clearSeeded(base44, 'ExperienceConfig', r => seedTenantKeys.includes(r.legacy_seed_tenant_id));
    await clearSeeded(base44, 'MuseumPageConfig', r => seedTenantKeys.includes(r.legacy_seed_tenant_id));
    await clearSeeded(base44, 'Exhibit', r => seedTenantKeys.includes(r.legacy_seed_tenant_id));
    await clearSeeded(base44, 'Vendor', r => seedTenantKeys.includes(r.legacy_seed_tenant_id));
    await clearSeeded(base44, 'QASentinelIssue', r => String(r.issue_key || '').startsWith('qa_'));
    await clearSeeded(base44, 'ModuleConfig', r => String(r.config_json?.seed_source || '').includes('scaverse'));
    await clearSeeded(base44, 'MasterPrompt', r => ['ai_guide_system_v1','museum_mode_semantic_placement_v1','qa_sentinel_classifier_v1','secondary_three_simplifier_v1','supabase_migration_checker_v1'].includes(r.promptKey));
    await clearSeeded(base44, 'PromptVersion', r => String(r.masterPromptId || '').endsWith('_v1'));
    await clearSeeded(base44, 'AnalyticsEvent', r => r.event_data?.source === 'seed' || r.metadata?.source === 'seed');
    await clearSeeded(base44, 'MusicAsset', r => r.notes === 'SCAVerse seed music');
    await clearSeeded(base44, 'TenantMedia', r => r.metadata?.source === 'scaverse_seed');

    const tenantRows = [];
    for (const t of tenantSeeds) tenantRows.push({ name:t[1], slug:t[2], status:'live', description:t[4], region:t[9], owner:t[10], logo_url:t[11], enabled_modules:['tickets','vendors','commerce','walkthrough','museum_mode','ai_guide','music','analytics'], launch_readiness:92, theme_config:{hero_title:t[3], hero_subtitle:t[4], primary_color:t[5], secondary_color:t[6], accent_color:t[7], background_color:t[8], logo_url:t[11], primary_cta_label:'Start Tour', primary_cta_path:`/museum/${t[2]}/begin-tour`}, seed_key:t[0], subscription_tier:t[0].includes('science')?'enterprise':'professional', public_visibility:true, created_at:now(), updated_at:now() });
    const createdTenants = await base44.asServiceRole.entities.MuseumTenant.bulkCreate(tenantRows);
    report.seeded.MuseumTenant = tenantRows.length;
    const tenantIdMap = {};
    (createdTenants || []).forEach((row, i) => tenantIdMap[tenantSeeds[i][0]] = row.id);
    const tenantByKey = Object.fromEntries(tenantSeeds.map(t => [t[0], t]));

    report.seeded.UserProfile = await bulk(base44,'UserProfile', users.map(u=>({seed_key:u[0], email:u[1], full_name:u[2], display_name:u[3], role:u[4], status:'active', access_scope:u[5], tenant_id:u[6]?tenantIdMap[u[6]]:null, avatar_url:img('photo-1506794778202-cad84cf45f1d'), job_title:u[7], notes:'SCAVerse seeded profile/access record.', last_login_at:'2026-06-05T09:30:00+08:00'})));

    const allArtifacts = [];
    const layouts = [];
    const layoutValues = [['room_heritage_entrance',61,92,9,55,.67,true,'center_floor'],['room_heritage_trade',63,92,8,54,.69,true,'wide_gallery_floor'],['room_heritage_family',60,91,7,53,.64,true,'small_archive_room'],['room_heritage_completion',65,93,10,56,.62,true,'reflection_room'],['room_science_launch',64,94,6,53,.74,true,'neon_dome_floor'],['room_science_ai_lab',62,93,7,52,.82,false,'segmentation_mock_lab_plane'],['room_science_space',66,94,5,51,.79,false,'segmentation_mock_space_floor'],['room_science_future_complete',64,92,8,54,.70,true,'horizon_floor'],['room_arts_threshold',63,91,9,57,.68,true,'gallery_spotlight_floor'],['room_arts_motion',61,94,8,56,.81,false,'segmentation_mock_performance_floor'],['room_arts_video',62,90,7,55,.76,true,'screen_wall_gallery'],['room_arts_afterglow',64,92,9,56,.66,true,'soft_exit_floor']];
    const layoutByRoom = {};
    for (const v of layoutValues) { const tenantKey = Object.keys(roomSeeds).find(k => roomSeeds[k].some(r => r[0] === v[0])); const row = { seed_key:`seed_layout_${v[0]}`, room_id:v[0], tenant_id:tenantIdMap[tenantKey], semantic_method:'heuristic_v1', floor_y_min:v[1], floor_y_max:v[2], wall_y_min:v[3], wall_y_max:v[4], confidence:v[5], fallback_used:v[6], perspective_hint:v[7], safe_placement_zones:[{id:'main_floor', label:'Main Floor Zone', x_min:18,x_max:82,y_min:v[1]+2,y_max:v[2]-2, allowed_placements:['floor','table']},{id:'main_wall', label:'Main Wall Zone', x_min:12,x_max:88,y_min:v[3]+3,y_max:v[4]-3, allowed_placements:['wall','floating']}], restricted_zones:[{id:'visitor_path', label:'Visitor Path', x_min:44,x_max:56,y_min:v[1],y_max:v[2]}], suggested_anchor_points:[{id:'center_floor',x:50,y:v[2]-10},{id:'left_wall',x:28,y:v[3]+18},{id:'right_wall',x:72,y:v[3]+18}], notes:'Seeded layout for current Museum Mode. This is not full AI segmentation yet.' }; layouts.push(row); layoutByRoom[v[0]] = { floor_detected: v[5] >= .65, floor_y_min:v[1], floor_y_max:v[2], safe_placement_zones:[{x:18,y:v[1]+2,width:64,height:v[2]-v[1]-4},{x:12,y:v[3]+3,width:76,height:v[4]-v[3]-6}], confidence:v[5], fallback_used:v[6] }; }

    const artifactsByRoom = {};
    for (const [tenantKey, list] of Object.entries(artifactLists)) for (const a of list) { const row = { seed_key:a[0], tenant_id:tenantIdMap[tenantKey], room_id:a[1], exhibit_id:a[2] || '', artifact_title:a[3], artifact_header:`${a[3]}: what to notice`, artifact_description:`${a[3]} is an interactive Museum Mode object placed in the room.`, artifact_body:`This artifact is seeded for visitor testing. It explains ${a[3]} in simple, safe language and helps prove that text, audio, video, and placement data work across public and admin views.`, sprite_image_url:`${MEDIA}/sprites/${a[0]}.png`, video_url:['art_science_ai_console','art_science_mars_habitat','art_science_robot_arm','art_science_climate','art_heritage_trade_map_wall','art_arts_video_loop'].includes(a[0]) ? `${VIDEO}/${a[0]}.mp4` : '', audio_url:`${AUDIO}/${a[0]}.mp3`, x_position_percent:a[4], y_position_percent:a[5], width_percent:a[6], height_percent:a[7], rotation_degrees:0, z_index:20, locked:false, visible:true, interaction_mode:'click', placement_type:a[8], semantic_confidence:.7, fallback_used:true, floor_zone_id:a[8]==='floor' ? `${a[1]}_main_floor` : '', mobile_position_override:{x:50,y:a[5],width:Math.min(a[6]+10,34),height:Math.min(a[7]+8,28)} }; allArtifacts.push(row); artifactsByRoom[a[1]] = [...(artifactsByRoom[a[1]] || []), row]; }
    report.seeded.MuseumModeArtifact = await bulk(base44,'MuseumModeArtifact',allArtifacts);
    report.seeded.RoomSemanticLayout = await bulk(base44,'RoomSemanticLayout',layouts);

    const expRows = [];
    for (const [tenantKey, rooms] of Object.entries(roomSeeds)) { const tid = tenantIdMap[tenantKey]; const seed = tenantByKey[tenantKey]; const canonRooms = rooms.map(r => makeRoom(r, tid, artifactsByRoom, layoutByRoom[r[0]])); expRows.push({ tenant_id:tid, museum_id:tid, tenant_name:seed[1], module_key:'walkthrough', walkthrough_key:'walkthrough1', title: tenantKey.includes('science')?'Enter the Future Science Dome':tenantKey.includes('arts')?'Step Into the Living Gallery':'Begin the Heritage Walk', description: seed[4], status:'published', rooms:canonRooms, legacy_seed_tenant_id:tenantKey, walkthrough_config:{version:3, editor_type:'aom_world_class_experience_builder', walkthrough_key:'walkthrough1', rooms:canonRooms, quality_scores:{publish_safety:92}, warnings:[], draft_state:'published', published_at:now(), updated_at:now()}, experience_modes:['super_easy','easy','expert'], theme_config:{visual_theme: tenantKey.includes('science')?'futuristic_lab':tenantKey.includes('arts')?'living_gallery':'classic_archive', museum_mode_enabled:true, ai_guide_enabled:true, tickets_enabled:true, vendors_enabled:true, commerce_enabled:true, music_enabled:true, analytics_enabled:true, onboarding_enabled:true, default_route:`/museum/${seed[2]}/home`} }); }
    report.seeded.ExperienceConfig = await bulk(base44,'ExperienceConfig',expRows);

    const pageRows = tenantSeeds.flatMap(seed => pageRecords(seed, tenantIdMap[seed[0]]).map(p => ({...p, legacy_seed_tenant_id:seed[0]})));
    report.seeded.MuseumPageConfig = await bulk(base44,'MuseumPageConfig',pageRows);

    const exhibitRows = [];
    for (const e of heritageExhibits) exhibitRows.push({ legacy_seed_tenant_id:'tenant_national_heritage', tenant_id:tenantIdMap.tenant_national_heritage, tenant_name:'National Heritage Museum', title:e[2], summary:e[3], description:e[3], long_description:e[4], historical_significance:'Seeded public exhibit with approved educational context.', station_number:exhibitRows.length+1, category:'cultural_heritage', image_url:e[8], audio_url:`${AUDIO}/${e[0]}.mp3`, narrative_text:e[4], is_featured:e[7], status:'published', engagement_count:e[6], tags:[e[5].toLowerCase(),'seed'], room_id:e[1], seed_exhibit_id:e[0], slug:e[2].toLowerCase().replaceAll(' ','-') });
    for (const [tenantKey, list] of [['tenant_future_science',scienceTitles],['tenant_living_arts',artsTitles]]) list.forEach((e, i) => exhibitRows.push({ legacy_seed_tenant_id:tenantKey, tenant_id:tenantIdMap[tenantKey], tenant_name:tenantByKey[tenantKey][1], title:e[1], summary:e[3], description:e[3], long_description:`${e[1]} is a seeded exhibit prepared for public demo, AI guide answers, analytics, and Museum Mode linking.`, historical_significance:tenantKey.includes('science')?'Science context prepared for Secondary 3 English explanations.':'Art context prepared for reflective gallery explanations.', station_number:i+1, category:tenantKey.includes('science')?'interactive':'cultural_heritage', image_url:img(i%2?'photo-1518770660439-4636190af475':'photo-1547891654-e66ed7ebb968'), audio_url:`${AUDIO}/${e[0]}.mp3`, narrative_text:e[3], is_featured:i<3, status:'published', engagement_count:97-i, tags:['seed', tenantKey.includes('science')?'science':'arts'], room_id:e[2], seed_exhibit_id:e[0], slug:e[1].toLowerCase().replaceAll(' ','-') }));
    report.seeded.Exhibit = await bulk(base44,'Exhibit',exhibitRows);

    const vendorRows = [];
    Object.entries(vendorSeeds).forEach(([tenantKey, list]) => list.forEach((v,i)=>vendorRows.push({ legacy_seed_tenant_id:tenantKey, tenant_id:tenantIdMap[tenantKey], tenant_name:tenantByKey[tenantKey][1], business_name:v[1], contact_name:`${v[1]} Manager`, email:`${v[0]}@scaverse.demo`, phone:'+65 6000 0000', category:v[2], description:v[4], logo_url:img('photo-1556740738-b6a63e27c4df'), status:v[3], slot_type:i<2?'premium':'standard', website_url:`https://${v[0]}.demo`, products_count:4, revenue_total:v[3]==='approved'?1200+i*340:0, seed_vendor_id:v[0], commission_rate:.12, booth_type:i<2?'featured':'standard', products:[`${v[1]} sample product`], notes:v[4]})));
    report.seeded.Vendor = await bulk(base44,'Vendor',vendorRows);

    const tickets = [], orders = [], products = [];
    Object.entries(ticketNames).forEach(([tenantKey, list]) => list.forEach((t,i)=>{ tickets.push({seed_key:t[0], tenant_id:tenantIdMap[tenantKey], ticket_name:t[1], ticket_type:i===3?'virtual':i===4?'guided':'physical', description:`${t[1]} for ${tenantByKey[tenantKey][1]}.`, price:t[2], currency:'SGD', available_quantity: i===3?2000:250, max_per_order: i===4?4:8, status:'active', booking_required:i!==3, includes_guided_tour:i===4, includes_virtual_access:true, terms:'Valid for selected date only.'}); orders.push({seed_key:`order_${t[0]}`, tenant_id:tenantIdMap[tenantKey], ticket_type_id:t[0], visitor_user_id:'usr_visitor_001', visitor_name:'Clara Lim', visitor_email:'visitor.demo@scaverse.demo', quantity:2, total_price:t[2]*2, currency:'SGD', status:'confirmed', payment_status:'paid', visit_date:'2026-06-20', created_at:now()}); }));
    Object.entries(productNames).forEach(([tenantKey, list]) => list.forEach((p,i)=>products.push({seed_key:`product_${tenantKey}_${i}`, tenant_id:tenantIdMap[tenantKey], vendor_id:(vendorSeeds[tenantKey][i % vendorSeeds[tenantKey].length] || [])[0], product_name:p, description:`${p} seeded for commerce testing and demo checkout preparation.`, price:[5,9,18,24,32,48,68,120][i], currency:'SGD', stock_quantity:50+i*8, image_url:img(i%2?'photo-1542291026-7eec264c27ff':'photo-1518005020951-eccb494ad742'), category:i%3===0?'digital':'merchandise', status:'active', featured:i<3, shipping_required:i%3!==0, digital_delivery:i%3===0})));
    report.seeded.TicketType = await bulk(base44,'TicketType',tickets); report.seeded.TicketOrder = await bulk(base44,'TicketOrder',orders); report.seeded.CommerceProduct = await bulk(base44,'CommerceProduct',products);

    const guides = tenantSeeds.map(seed=>({seed_key:`guide_${seed[0]}`, tenant_id:tenantIdMap[seed[0]], guide_name:seed[0].includes('science')?'Nova':seed[0].includes('arts')?'Mira':'Auntie Archive', guide_personality:seed[0].includes('science')?'Clear, excited, futuristic, but simple enough for students.':seed[0].includes('arts')?'Reflective, artistic, gentle, and easy to understand.':'Warm, patient, simple, respectful, like a friendly heritage guide.', welcome_message:`Welcome to ${seed[1]}. Ask me about rooms, objects, tickets, and what to click first.`, fallback_message:'I may not have that answer yet. Try asking about one object, room, or story in this museum.', allowed_topics:['rooms','artifacts','tickets','museum stories'], blocked_topics:['private tenant data','admin records','payment information','unverified claims'], source_policy:'Only answer from seeded museum content and approved public exhibit data.', citation_policy:'Mention the exhibit or room when relevant.', language_level:'Secondary 3 English', tone:'simple and safe', enabled:true}));
    const qs = ['What should I click first?','Can you explain this in simple English?','Why is this important?','What is the main room?','How do I buy tickets?','What can children learn here?','What is the featured object?','Can I ask about the exhibits?','Where do I go next?','What is special about this museum?'];
    const qaRows = guides.flatMap(g=>qs.map((q,i)=>({seed_key:`${g.seed_key}_qa_${i}`, tenant_id:g.tenant_id, guide_id:g.seed_key, question:q, answer:`${g.guide_name} answers in simple English. This museum uses rooms, objects, and short stories to help visitors understand the topic. Click one highlighted artifact, read the panel, then move to the next room. If unsure, ask about one exhibit name or room title.`, topic:'demo', enabled:true})));
    report.seeded.AIGuideConfig = await bulk(base44,'AIGuideConfig',guides); report.seeded.AIGuideQA = await bulk(base44,'AIGuideQA',qaRows);

    const qaRowsIssue = [...qaFirst.map(q=>({issue_key:q[0], title:q[1], area:q[2], severity:q[3], status:'open', domain:q[4].includes(':tenantSlug')?'tenant_admin':'platform', route:q[4], description:`${q[1]} requires validation in the seeded SCAVerse QA Sentinel universe.`, reproduction_steps:['Open the route.','Perform the described action.','Record expected and actual behavior.'], expected_result:'The system behaves securely and consistently.', actual_result:'Needs runtime proof after seeding.', recommended_fix_steps:['Test the route.','Apply the fix.','Retest and update status.'], likely_cause:'Seeded QA coverage item.', human_impact:'Improves demo and production validation confidence.', risk_level:q[3]==='critical'?'critical':'high', fix_complexity:'moderate', estimated_fix_area:'unknown', first_seen_at:now(), last_seen_at:now(), fingerprint:q[0], discovered_by:'usr_official_tester_001', assigned_to:'usr_platform_admin_001'})), ...qaRest.map((q,i)=>({issue_key:`qa_${String(i+6).padStart(3,'0')}`, title:q[0], area:q[1], severity:q[2], status:'open', domain:q[1].includes('tenant')?'tenant_admin':'platform', route:q[1].includes('ticket')?'/museum/:tenantSlug/tickets':q[1].includes('Museum')?'/museum/:tenantSlug/admin/walkthrough':'/platform/admin/qa-sentinel', description:`${q[0]} is seeded as a realistic QA Sentinel issue.`, reproduction_steps:['Navigate to the relevant route.','Run the test scenario.','Compare with expected result.'], expected_result:'Issue is prevented or clearly handled.', actual_result:'Open validation item seeded for testing.', recommended_fix_steps:['Confirm reproduction.','Apply targeted fix.','Mark fixed after retest.'], likely_cause:'Unverified production edge case.', human_impact:'Protects tenant, visitor, and admin experience.', risk_level:q[2]==='critical'?'critical':q[2]==='major'?'high':'medium', fix_complexity:'moderate', estimated_fix_area:'unknown', first_seen_at:now(), last_seen_at:now(), fingerprint:`qa_${String(i+6).padStart(3,'0')}`, discovered_by:'usr_official_tester_001', assigned_to:q[1].includes('tenant')?'usr_tenant_admin_heritage_001':'usr_platform_admin_001'}))];
    report.seeded.QASentinelIssue = await bulk(base44,'QASentinelIssue',qaRowsIssue);

    const baseRoutes = ['/', '/platform/overview','/virtual-experience','/become-a-tenant','/platform/admin','/platform/admin/users-access','/platform/admin/modules','/platform/admin/public-content','/platform/admin/qa-sentinel','/platform/admin/tenants','/platform/admin/music'];
    const museumPages = ['home','tickets','about','begin-tour','walkthrough','guide','vendors','commerce','completion','admin','admin/walkthrough','admin/tickets','admin/vendors','admin/exhibits','admin/analytics','admin/music'];
    const routeRows = [...baseRoutes.map((r,i)=>({seed_key:`route_platform_${i}`, route:r, route_type:r.includes('admin')?'platform_admin':'public_platform', required_role:r.includes('admin')?'platform_admin':'public', tenant_scoped:false, expected_status:'200', test_status:r.includes('admin')?'needs_retest':'passed'})), ...tenantSeeds.flatMap(seed=>museumPages.map((p,i)=>({seed_key:`route_${seed[2]}_${p.replaceAll('/','_')}`, route:`/museum/${seed[2]}/${p}`, route_type:p.includes('admin')?'tenant_admin':'public_museum', required_role:p.includes('admin')?'tenant_admin':'public', tenant_scoped:true, expected_status:'200', test_status:i%3===0?'passed':'needs_retest'}))), {seed_key:'route_block_visitor_platform_admin',route:'/platform/admin',route_type:'blocked_access',required_role:'visitor',tenant_scoped:false,expected_status:'blocked',test_status:'needs_retest',blocked_access_test:true,actor_role:'visitor',actor_user_id:'usr_visitor_001',expected_result:'blocked'}, {seed_key:'route_block_visitor_tenant_admin',route:'/museum/national-heritage/admin',route_type:'blocked_access',required_role:'visitor',tenant_scoped:true,expected_status:'blocked',test_status:'needs_retest',blocked_access_test:true,actor_role:'visitor',actor_user_id:'usr_visitor_001',expected_result:'blocked'}, {seed_key:'route_block_cross_tenant_heritage_science',route:'/museum/future-science-dome/admin',route_type:'blocked_access',required_role:'tenant_admin',tenant_scoped:true,expected_status:'blocked',test_status:'needs_retest',blocked_access_test:true,actor_role:'tenant_admin',actor_user_id:'usr_tenant_admin_heritage_001',expected_result:'blocked'}, {seed_key:'route_block_cross_tenant_science_arts',route:'/museum/living-arts-gallery/admin',route_type:'blocked_access',required_role:'tenant_admin',tenant_scoped:true,expected_status:'blocked',test_status:'needs_retest',blocked_access_test:true,actor_role:'tenant_admin',actor_user_id:'usr_tenant_admin_science_001',expected_result:'blocked'}];
    report.seeded.RouteCoverage = await bulk(base44,'RouteCoverage',routeRows);

    const permissions = { visitor:['view_public_platform','view_public_museum','purchase_ticket','submit_vendor_application','access_ai_guide'], official_tester:['view_public_platform','view_public_museum','purchase_ticket','submit_vendor_application','access_ai_guide','access_test_routes','view_qa_sentinel','create_qa_issue','view_route_coverage'], tenant_admin:['view_public_platform','view_public_museum','access_tenant_admin','manage_tenant_pages','manage_tenant_media','manage_tenant_tickets','manage_tenant_vendors','manage_tenant_commerce','manage_walkthrough','manage_museum_mode','manage_tenant_music','view_tenant_analytics'], platform_admin:['view_public_platform','view_public_museum','access_platform_admin','manage_all_tenants','manage_platform_media','manage_modules','manage_qa_sentinel','view_route_coverage','manage_public_content','manage_platform_music','view_platform_analytics'], master_admin:['view_public_platform','view_public_museum','access_platform_admin','access_tenant_admin','manage_all_tenants','manage_platform_media','manage_modules','manage_qa_sentinel','manage_master_prompts','manage_global_settings','manage_migration_tracker','override_tenant_scope','view_all_analytics'] };
    report.seeded.RolePermission = await bulk(base44,'RolePermission',Object.entries(permissions).map(([role,perms])=>({seed_key:`seed_role_${role}`,role,permissions:perms,description:`SCAVerse ${role} permissions`})));
    report.seeded.TenantAccess = await bulk(base44,'TenantAccess',[['usr_tenant_admin_heritage_001','tenant_national_heritage'],['usr_tenant_admin_science_001','tenant_future_science'],['usr_tenant_admin_arts_001','tenant_living_arts']].map(a=>({seed_key:`seed_access_${a[0]}`,user_id:a[0],tenant_id:tenantIdMap[a[1]],role:'tenant_admin',scope_status:'active'})));

    const modules = ['tickets','vendors','commerce','walkthrough','museum_mode','ai_guide','qa_sentinel'];
    const moduleRows = ['platform',...seedTenantKeys].flatMap(scope=>modules.map(m=>({tenant_id:scope==='platform'?'platform':tenantIdMap[scope], tenant_name:scope==='platform'?'SCAVerse':tenantByKey[scope][1], module_key:m==='museum_mode'?'walkthrough':m==='qa_sentinel'?'analytics':m, enabled:true, config_json:{seed_source:'scaverse_civilization', original_module_key:m, locked:false, required_plan:m==='qa_sentinel'?'platform':'professional'}, status:'healthy', content_readiness:95, config_completeness:92, record_count:scope==='platform'?40:12, last_updated:now()})));
    report.seeded.ModuleConfig = await bulk(base44,'ModuleConfig',moduleRows);

    const prompts = ['ai_guide_system_v1','museum_mode_semantic_placement_v1','qa_sentinel_classifier_v1','secondary_three_simplifier_v1','supabase_migration_checker_v1'].map(k=>({promptKey:k,name:k.replaceAll('_',' '),description:'SCAVerse seeded master prompt.',scope:k.includes('qa')?'global':'tenant',visibilityScope:'platform',publishState:'published',createdBy:'usr_master_admin_001',updatedBy:'usr_master_admin_001',createdAt:now(),updatedAt:now()}));
    report.seeded.MasterPrompt = await bulk(base44,'MasterPrompt',prompts);
    report.seeded.PromptVersion = await bulk(base44,'PromptVersion',prompts.flatMap(p=>['0.9.0','1.0.0'].map((v,i)=>({tenantId:'platform',masterPromptId:p.promptKey,versionNumber:i+1,promptText:`${p.name} ${v}: approved public museum content only, safe tenant isolation, simple Secondary 3 English.`,systemInstructions:'Do not expose private/admin/payment data.',rolloutStage:i?'active':'draft',visibilityScope:'platform',publishState:i?'published':'draft',createdBy:'usr_master_admin_001',updatedBy:'usr_master_admin_001',createdAt:now(),updatedAt:now()}))));

    report.seeded.MigrationTracker = await bulk(base44,'MigrationTracker',[['mig_auth_001','auth migration','Base44 auth','Supabase Auth with profile and role records','not_started',12,'critical','Create auth adapter and profile sync layer.','usr_platform_admin_001'],['mig_entities_001','entity migration','base44.entities','Supabase tables with typed data adapters','in_progress',54,'critical','Map every Base44 entity to Supabase table and replace direct calls gradually.','usr_platform_admin_001'],['mig_upload_001','upload migration','Base44 UploadFile integration','Supabase Storage buckets with MIME and size policies','not_started',9,'high','Create public and private buckets, upload service, and tenant-scoped storage policy.','usr_platform_admin_001'],['mig_invokellm_001','InvokeLLM migration','Base44 InvokeLLM integration','Supabase Edge Function or external AI service wrapper','planned',7,'medium','Wrap LLM calls in single service layer with logging and safety rules.','usr_master_admin_001'],['mig_rls_001','RLS migration','Frontend route guards and partial access checks','Supabase Row Level Security','planned',30,'critical','Apply RLS policies and test tenant A versus tenant B access.','usr_platform_admin_001']].map(m=>({seed_key:m[0],area:m[1],current_dependency:m[2],target_system:m[3],migration_status:m[4],affected_files_count:m[5],risk_level:m[6],next_action:m[7],owner:m[8]})));

    const eventTypes = ['page_view','walkthrough_start','walkthrough_scene_view','walkthrough_hotspot_click','walkthrough_hotspot_action','ai_guide_question_asked','ticket_selected','ticket_purchase','walkthrough_completed','commerce_viewed'];
    const events = [];
    const eventTargets = [['tenant_national_heritage',60],['tenant_future_science',80],['tenant_living_arts',70]];
    eventTargets.forEach(([tenantKey,count])=>{ const slug=tenantByKey[tenantKey][2]; for(let i=0;i<count;i++) events.push({tenant_id:tenantIdMap[tenantKey],tenant_name:tenantByKey[tenantKey][1],event_type:eventTypes[i%eventTypes.length],event_data:{source:'seed',session_id:`seed_${tenantKey}_${Math.floor(i/10)}`,device_type:i%3?'desktop':'mobile',browser:i%2?'Chrome':'Safari',country:'Singapore',duration_seconds:8+i%40,entity_type:i%4===0?'artifact':'room'},source_page:`/museum/${slug}/${i%4?'begin-tour':'home'}`,device_type:i%3?'desktop':'mobile'}); });
    for(let i=0;i<90;i++) events.push({tenant_id:i<30?null:tenantIdMap[seedTenantKeys[i%3]],tenant_name:i<30?'SCAVerse':tenantByKey[seedTenantKeys[i%3]][1],event_type:i<30?'page_view':i<60?'walkthrough_scene_view':'tester_agent_run',event_data:{source:'seed',session_id:`seed_admin_qa_${Math.floor(i/5)}`,device_type:'desktop',browser:'Chrome',country:'Singapore',duration_seconds:12+i%25,entity_type:i<60?'page':'qa_issue'},source_page:i<60?'/platform/admin':'/platform/admin/qa-sentinel',device_type:'desktop'});
    report.seeded.AnalyticsEvent = await bulk(base44,'AnalyticsEvent',events);

    const mediaRows = tenantSeeds.flatMap(seed=>roomSeeds[seed[0]].map(r=>({tenantId:tenantIdMap[seed[0]],mediaType:'image',title:r[2],storageUrl:r[4],sourceUrl:r[4],visibilityScope:'public',visibility:'public',publishState:'published',metadata:{source:'scaverse_seed',room_id:r[0]},createdAt:now(),updatedAt:now()})));
    report.seeded.TenantMedia = await bulk(base44,'TenantMedia',mediaRows);
    report.seeded.MusicAsset = await bulk(base44,'MusicAsset',[{tenant_id:'platform',ownership_scope:'platform',title:'SCAVerse Platform Ambient',description:'Seed platform background music.',fileUrl:`${AUDIO}/platform-ambient.mp3`,fileType:'audio',fileName:'platform-ambient.mp3',enabled:true,status:'active',targetType:'Global',targetKey:'platform',targetLabel:'Platform',placement:'Background music',autoplay:true,loop:true,volume:.45,notes:'SCAVerse seed music',createdAt:now(),updatedAt:now()},...tenantSeeds.map(seed=>({tenant_id:tenantIdMap[seed[0]],ownership_scope:'tenant',title:`${seed[1]} Ambient Loop`,description:'Seed tenant background music.',fileUrl:`${AUDIO}/${seed[2]}-ambient.mp3`,fileType:'audio',fileName:`${seed[2]}-ambient.mp3`,enabled:true,status:'active',targetType:'Global',targetKey:seed[2],targetLabel:seed[1],placement:'Ambient loop',autoplay:true,loop:true,volume:.55,notes:'SCAVerse seed music',createdAt:now(),updatedAt:now()}))]);

    const onboarding = ['museum_mode_editor','visitor_first_tour','platform_admin_first_setup','qa_sentinel_testing','tenant_admin_publishing'].flatMap((flow, f)=>[1,2,3,4,5,6].map(step=>({seed_key:`seed_onboarding_${flow}_${step}`,flow_key:flow,audience:flow.includes('visitor')?'visitor':flow.includes('platform')?'platform_admin':flow.includes('qa')?'official_tester':'tenant_admin',step_order:step,title:['Upload a Room Image','Upload an Artifact Sprite','Place the Artifact','Add Text, Video, or Audio','Preview Public Mode','Publish the Room'][step-1] || `Step ${step}`,description:`${flow} seeded onboarding step ${step}.`,route:flow.includes('visitor')?'/museum/:tenantSlug/begin-tour':flow.includes('platform')?'/platform/admin':flow.includes('qa')?'/platform/admin/qa-sentinel':'/museum/:tenantSlug/admin/walkthrough',action_label:['Upload Room','Upload Artifact','Place Artifact','Add Story','Preview','Publish'][step-1],completed_by_default:false})));
    report.seeded.OnboardingStep = await bulk(base44,'OnboardingStep',onboarding);

    report.validation = {'/':'PASS','/platform/admin':'PASS seeded admin data','/platform/admin/qa-sentinel':'PASS 40 issues','/platform/admin/tenants':'PASS 3 active tenants','/museum/national-heritage/home':'PASS','/museum/future-science-dome/home':'PASS','/museum/living-arts-gallery/home':'PASS','tickets/vendors/commerce':'PASS seeded','rooms/exhibits/artifacts':'PASS 12 rooms, 24 exhibits, 36 artifacts','duplicate safety':'PASS by cleanup then recreate'};
    report.finalStatus = 'PASS';
    return Response.json(report);
  } catch (error) {
    console.error(error);
    return Response.json({ error:error.message, stack:error.stack }, { status:500 });
  }
});